### ISSUE TITLE
Is the pretrained model available?

### ISSUE THREAD

**Issue by DeepRunner** [alibaba-edu/simple-effective-text-matching-pytorch#2]
Hi, Is the pretrained model available? And how many hours is a typical training  taking (e.g.on SNL)?

**Comment by hitvoice** [comment]
It takes 2h45m to train an RE2 model for SNLI on a single Nvidia Tesla P100. Pretrained models are kept but not published because the results should be easily reproduced.

**Comment by DeepRunner** [comment]
Thanks
