### ISSUE TITLE
How can I solve the problem "RuntimeError: Mask tensor can take 0 and 1 values only at..." with Pytorch 1.2.0

### ISSUE THREAD

**Issue by muguruzawang** [alibaba-edu/simple-effective-text-matching-pytorch#5]
Excuse  me, I encounter the problem that "RuntimeError: Mask tensor can take 0 and 1 values only at /pytorch/aten/src/TH/generic/THTensorEvenMoreMath.cpp:580"  when training the model with Pytorch 1.2.0.

Do you have any solution to this problem? Thanks.

**Comment by muguruzawang** [comment]
OK，I solved it.

**Comment by hitvoice** [comment]
Sorry for the late reply. Glad to see you solved it. :)

**Comment by bott1eee** [comment]
> OK，I solved it.

Can you please tell me how you solved this problem? thanks!!!

**Comment by hitvoice** [comment]
@bott1eee Switching to pytorch 1.0.1 will solve the problem. I'll update the latest version compatible implementation when I get some time.

**Comment by hitvoice** [comment]
@bott1eee fix in the master branch (05d572e30801b235e989c78c95dd24d5f5d35f74)
