### ISSUE TITLE
数据下载不了

### ISSUE THREAD

**Issue by Boye-Z** [alibaba-edu/simple-effective-text-matching-pytorch#7]
链接数据下载不了，是否可以数据分享一下981276301@qq.com

**Comment by hitvoice** [comment]
你指的具体哪个数据集？

**Comment by xiuzhilu** [comment]
quora的数据集下载不了，大佬还有其他的下载链接吗？

**Comment by hitvoice** [comment]
https://github.com/zhiguowang/BiMPM 中的Quora数据集链接我刚才试了下还是可以下载的，科学上网就可以
