### ISSUE TITLE
这个源码可以在windows环境下运行吗？

### ISSUE THREAD

**Issue by mingtian26** [alibaba-edu/simple-effective-text-matching-pytorch#8]

**Comment by mingtian26** [comment]
我在运行源码时有一个不能转换为float的错误，发现是wikiqa 需要编译 evaluation scripts，我用的是windows环境， 请问windows下怎么编译生成 evaluation scripts ?

**Comment by hitvoice** [comment]
可以参考这个回答：https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows
