### ISSUE TITLE
运行训练模型报错

### ISSUE THREAD

**Issue by super017** [alibaba-edu/simple-effective-text-matching-pytorch#9]
我在运行训练代码时报错ImportError: cannot import name 'Module'

**Comment by hitvoice** [comment]
有完整的报错信息（包含stack trace的那种）吗？

**Comment by super017** [comment]
> Traceback (most recent call last):
  File "/home/lis/ls/dec_cluster/RE2_textmatch/train.py", line 8, in <module>
    from model import RE2
  File "/home/lis/ls/dec_cluster/RE2_textmatch/model.py", line 3, in <module>
    from modules import Module, ModuleList, ModuleDict
ImportError: cannot import name 'Module'

Process finished with exit code 1

我看到在modules文件夹中也确实没有Module, ModuleList, ModuleDict这三个代码文件或其他的类、函数等，在其他代码文件中也没有找到这三个

**Comment by super017** [comment]
我已经找到问题的关键了，我有一个代码文件没有看到，就是那个__init__.py，导致导入的时候找不到相关的类

**Comment by hitvoice** [comment]
好的，解决了就好
